# Generated by Django 3.1.3 on 2020-11-14 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pathway', '0002_displaystage_firm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.stage')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('question_pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.questionpack')),
            ],
        ),
        migrations.CreateModel(
            name='FirmQuestionPackConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathway.firm')),
                ('question_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionpack')),
            ],
        ),
    ]
