# Generated by Django 3.1.3 on 2020-11-15 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionpack_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmquestionpackconnector',
            name='question_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmquestions', to='questions.questionpack'),
        ),
    ]
