# Generated by Django 3.1.3 on 2020-11-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionpack', to='questions.questionpack'),
        ),
    ]
