# Generated by Django 3.1.3 on 2020-11-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='estimated_time',
            field=models.IntegerField(default=5, verbose_name='Estimated time in mins'),
        ),
    ]
