# Generated by Django 3.1.3 on 2020-11-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='my_answer',
            field=models.TextField(null=True),
        ),
    ]
