# Generated by Django 3.1.3 on 2020-11-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20201115_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
