# Generated by Django 3.1.3 on 2020-11-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='streak',
            field=models.IntegerField(default=1),
        ),
    ]
