# Generated by Django 3.1.3 on 2020-11-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_userfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfirm',
            name='order',
            field=models.IntegerField(default=1000),
        ),
    ]
